Load definitions
DiamondLightSource/messagebus pull request #10
Opened 2024-09-02 13:59 UTC by daurer

depends on #7, #8 and #9

2024-09-24 15:50 UTC, garryod requested changes

2024-09-24 15:50 UTC, garryod commented on charts/rabbitmq/templates/rabbitmq-load-definition-sealed-secret.yaml
> +  namespace: {{ .Release.NameSpace }}
```suggestion
  namespace: {{ .Release.Namespace }}
```

2024-09-26 12:53 UTC, garryod requested changes

2024-09-26 12:53 UTC, garryod commented on charts/rabbitmq/templates/rabbitmq-load-definition-secret.yaml
> +          "name": "user",
Should we call the admin `admin`?

2024-09-26 12:53 UTC, garryod commented on rabbitmq-app.yaml
> +      jqPathExpressions
```suggestion
      jqPathExpressions:
```

2024-09-26 12:57 UTC, daurer commented on charts/rabbitmq/templates/rabbitmq-erlang-secret.yaml
> +    rabbitmq-erlang-cookie: AgAJ7RciGKjdfZlneoc9eD79hD3aCPVCRrUjhw7az7+hDaOLpXQpCJK+N7rnmCvJUIcqPbA7yQTURF6gGW5tcPyVb1bt2iEzImpgIRoFWTm7/pEmJqEuxPWuLZhZP48fPj+39rRX4LHJikDStGDSQdrsOTehQQ0Av5CfTBLDVDJ
Yes, that would make sense. Maybe we could make a separate PR for this. see #13

2024-09-27 10:49 UTC, daurer commented on charts/rabbitmq/templates/rabbitmq-load-definition-secret.yaml
> +          "name": "user",
done

2024-09-27 10:50 UTC, daurer commented on charts/rabbitmq/templates/rabbitmq-load-definition-secret.yaml
> +  load_definition.json: |-
done

2024-09-27 15:00 UTC, merged